version: '3'

services:
  survey:
    build: server/
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'

  results:
    build: frontend/
    depends_on:
      - 'server'
    ports:
      - '3000:3000'

  database:
    image: postgres:latest